kind: Service
apiVersion: v1
metadata:
  name: vaman-helidon-mp-demo
  labels:
    app: vaman-helidon-mp-demo
spec:
  type: ClusterIP
  selector:
    app: vaman-helidon-mp-demo
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vaman-helidon-mp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaman-helidon-mp-demo
  template:
    metadata:
      labels:
        app: vaman-helidon-mp-demo
        version: v1
    spec:
      containers:
      - name: vaman-helidon-mp-demo
        image: vaman-helidon-mp-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
